from .iq_get_business_features import GetBusinessFeatureIqProtocolEntity,GetBusinessFeatureResultIqProtocolEntity
from .iq_get_business_name import GetBusinessNameIqProtocolEntity,GetBusinessNameResultIqProtocolEntity
from .iq_set_business_name import SetBusinessNameIqProtocolEntity,SetBusinessNameResultIqProtocolEntity
from .iq_set_business_profile import SetBusinessProfileIqProtocolEntity
from .iq_get_business_profile import GetBusinessProfileIqProtocolEntity