# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consonance/proto/cert.proto
"""Generated protocol buffer code."""
from typing import Any, Optional, Dict, List, Tuple, Union, Callable
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63onsonance/proto/cert.proto\x12\x08whatsapp\"\x90\x01\n\x10NoiseCertificate\x12\x0f\n\x07\x64\x65tails\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x1aX\n\x07\x44\x65tails\x12\x0e\n\x06serial\x18\x01 \x01(\r\x12\x0e\n\x06issuer\x18\x02 \x01(\t\x12\x0f\n\x07\x65xpires\x18\x03 \x01(\x04\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12\x0b\n\x03key\x18\x05 \x01(\x0c\"\x9a\x02\n\tCertChain\x12\x32\n\x04leaf\x18\x01 \x01(\x0b\x32$.whatsapp.CertChain.NoiseCertificate\x12:\n\x0cintermediate\x18\x02 \x01(\x0b\x32$.whatsapp.CertChain.NoiseCertificate\x1a\x9c\x01\n\x10NoiseCertificate\x12\x0f\n\x07\x64\x65tails\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x1a\x64\n\x07\x44\x65tails\x12\x0e\n\x06serial\x18\x01 \x01(\r\x12\x15\n\rissuer_serial\x18\x02 \x01(\r\x12\x0b\n\x03key\x18\x03 \x01(\x0c\x12\x12\n\nnot_before\x18\x04 \x01(\x04\x12\x11\n\tnot_after\x18\x05 \x01(\x04\x42\x14\n\x12\x63om.whatsapp.proto')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consonance.proto.cert_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022com.whatsapp.proto'
  _NOISECERTIFICATE._serialized_start=42
  _NOISECERTIFICATE._serialized_end=186
  _NOISECERTIFICATE_DETAILS._serialized_start=98
  _NOISECERTIFICATE_DETAILS._serialized_end=186
  _CERTCHAIN._serialized_start=189
  _CERTCHAIN._serialized_end=471
  _CERTCHAIN_NOISECERTIFICATE._serialized_start=315
  _CERTCHAIN_NOISECERTIFICATE._serialized_end=471
  _CERTCHAIN_NOISECERTIFICATE_DETAILS._serialized_start=371
  _CERTCHAIN_NOISECERTIFICATE_DETAILS._serialized_end=471
# @@protoc_insertion_point(module_scope)
