from .iq_get_shortlink import GetShortLinkIqProtocolEntity,GetShortLinkResultIqProtocolEntity
from .iq_reset_shortlink import ResetShortLinkIqProtocolEntity,ResetShortLinkResultIqProtocolEntity
from .iq_setmsg_shortlink import SetMsgShortLinkIqProtocolEntity,SetMsgShortLinkResultIqProtocolEntity
from .iq_decode_shortlink import DecodeShortLinkIqProtocolEntity,DecodeShortLinkResultIqProtocolEntity

