from .attributes_syncd_patch import SyncdPatchAttribute
from .attributes_syncd_mutation import SyncdMutationAttribute
from .attributes_syncd_record import SyncdRecordAttribute
from .attributes_syncd_version import SyncdVersionAttribute
from .attributes_syncd_value import SyncdValueAttribute
from .attributes_syncd_key_id import SyncdKeyIdAttribute
from .attributes_syncd_index import SyncdIndexAttribute
from .attributes_syncd_exit_code import SyncdExitCodeAttribute
from .attributes_syncd_external_blob_reference import SyncdExternalBlobReferenceAttribute


from .attributes_sync_action_locale_setting import SyncActionLocaleSettingAttribute
from .attributes_sync_action_pushname_setting import SyncActionPushnameSettingAttribute
from .attributes_sync_action_time_format_action import SyncActionTimeFormatActionAttribute
from .attributes_sync_action_primary_version import SyncActionPrimaryVersionActionAttribute
from .attributes_sync_action_nux_action import SyncActionNuxActionAttribute

from .attributes_sync_action_value import SyncActionValueAttribute
from .attributes_sync_action_contact_action import SyncActionContactActionAttribute
from .attributes_sync_action_locale_setting import SyncActionLocaleSettingAttribute
from .attributes_sync_action_pushname_setting import SyncActionPushnameSettingAttribute

from .attributes_sync_action_data import SyncActionDataAttribute

from .attributes_syncd_patch import SyncdPatchAttribute